import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkiedIn App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Linkied In Clone</h2>
    </div>
  );
}
