import { signOut } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkiedIn App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={signOut}>Sign out</button>
      </div>
    </div>
  );
}
